#!/bin/sh

sudo apt-get update
sudo apt-get install build-essential libevent-dev

wget https://Launchpad.net/libmemcached/1.0/1.0.18/+download/libmemcached-1.0.18.tar.gz
tar xvf libmemcached-1.0.18.tar.gz
cd libmemcached-1.0.18
export LDFLAGS=-lpthread
./configure --enable-memaslap &&  make clients/memaslap



cd ..
mkdir config
nano config/smallvalue.cfg

#libmemcached-1.0.18/clients/memaslap -s 10.0.0.13:11212 -T 64 -c 64 -o 0.9 -S 1s -t 1m -F config/smallvalue.cfg
